name: 'Docman homework Judge Action'
description: 'Oniline Judge for Docman homework of PKU software course'
author: pku-software
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: "2.8.8"
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.action_path }}/requirements.txt
          python ${{ github.action_path }}/src/main.py ${{ github.workspace }}
      shell: bash
