name: 'Docman homework Judge Action'
description: 'Online Judge for Docman homework of PKU software course'
author: pku-software
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.action_path }}/requirements.txt
          python ${{ github.action_path }}/src/main.py --input_dir ${{ github.action_path }}/inputs --citation_dir ${{ github.action_path }}/citations ${{ github.workspace }}
      shell: bash
