name: 'Docman homework Judge Action'
description: 'Online Judge for Docman homework of PKU software course'
author: pku-software
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Check CMake version
      id: check-cmake
      run: |
        CURRENT_VERSION=$(cmake --version | head -n1 | awk '{print $3}')
        REQUIRED_VERSION="3.30.0"

        if [ "$(printf "%s\n%s" "$CURRENT_VERSION" "$REQUIRED_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
          echo "setup-cmake-action=true" >> $GITHUB_OUTPUT
        else
          echo "setup-cmake-action=false" >> $GITHUB_OUTPUT
        fi
    - name: Setup cmake
      if: steps.check-cmake.outputs.setup-cmake-action == 'true'
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.30.x'
    - run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.action_path }}/requirements.txt
          python ${{ github.action_path }}/src/main.py --input_dir ${{ github.action_path }}/inputs --citation_dir ${{ github.action_path }}/citations ${{ github.workspace }}
      shell: bash
